### ISSUE TITLE
Is globMatch going to be implemented soon?

### ISSUE THREAD

**Issue by meekotherogue** [casbin/SwiftCasbin#23]
I was just wondering if there were any plans to implement the [globMatch function](https://github.com/casbin/SwiftCasbin/blob/master/Sources/Casbin/Util/MatchFunctions.swift#L106 ) in `MatchFunctions.swift`? Our model was designed before we realized `globMatch` wasn't supported yet. If not, are you open to contributions to this project? Thanks!

**Comment by hsluoyz** [comment]
Hi @meekotherogue , PR is welcome!

**Comment by hsluoyz** [comment]
@feloraaa plz take a look
